name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build .

    - name: Test
      env:
        AWS_BUCKET_NAMESPACE: etcgithub
        AWS_PROFILE: github-ci
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        mkdir ~/.aws
        > ~/.aws/credentials echo "[${AWS_PROFILE}]"
        > ~/.aws/credentials echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}"
        > ~/.aws/credentials echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}"
        go test -v .
